spring:
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://db:5432/issues-deployer
    username: issues-deployer
    password: YourStrongSecretPassword
  quartz:
      # job-store-type: jdbc
      properties:
        # org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        org.quartz.threadPool.threadCount: 5
logging.level:
  com.vaddemgen.issuesdeployer.base.scheduler.applicationlayer.job: TRACE
