server:
  port: 8081
spring:
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://100.0.10.2:5432/issues-deployer
    username: issues-deployer
    password: issues-deployer
  redis:
    host: 100.0.10.3
    password: issues-deployer
#logging.level.org.hibernate:
#  SQL: DEBUG
#  type.descriptor.sql.BasicBinder: TRACE