spring:
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://db:5432/issues-deployer
    username: issues-deployer
    password: YourStrongSecretPassword